#!/bin/bash
echo -e "\e[94m               +                
\e[94m               #                
\e[94m              ###               
\e[94m             #####              
\e[94m             ######             \e[1;94mUser: \e[0m$USER
\e[94m            ; #####;            \e[1;94mHost: \e[0m$HOSTNAME
\e[94m           +##.#####            \e[1;94mShell: \e[0m$SHELL
\e[94m          +##########           \e[1;94mUptime: \e[0m$($_CMD uptime | sed s/,//g | awk '{print $3}')
\e[94m         ######\e[36m#####\e[94m##;         \e[1;94mEditor: \e[0m$EDITOR
\e[94m        ###\e[36m############\e[94m+        \e[1;94mKernel Release: \e[0m$(uname -r)
\e[94m       #\e[36m######   #######        \e[1;94mCPU: \e[0m$(awk 'BEGIN{FS=": "}/model name/ { print $2; exit }' /proc/cpuinfo)
\e[36m     .######;     ;###;\`\".      \e[1;94mPackages (native): \e[0m$(touch /tmp/NCACHE;LOGSIZE=$(wc -c /var/log/pacman.log | awk '{print $1}') && if [ "$(cat /tmp/NCACHE)" == "$LOGSIZE" ] && [ -f /tmp/NVAL ];then cat /tmp/NVAL;else echo "$LOGSIZE">/tmp/NCACHE;tee /tmp/NVAL <<< $(pacman -Qqn | wc -l);fi)
\e[36m    .#######;     ;#####.       \e[1;94mPackages (foreign): \e[0m$(touch /tmp/MCACHE;LOGSIZE=$(wc -c /var/log/pacman.log | awk '{print $1}') && if [ "$(cat /tmp/MCACHE)" == "$LOGSIZE" ] && [ -f /tmp/MVAL ];then cat /tmp/MVAL;else echo "$LOGSIZE">/tmp/MCACHE;tee /tmp/MVAL <<< $(pacman -Qqm | wc -l);fi)
\e[36m    #########.   .########\`     \e[1;94mTerminal: \e[0m$TERM
\e[36m   ######'           '######    
\e[36m  ;####                 ####;   
\e[36m  ##'                     '##   
\e[36m #'                         \`#  
\x1b[0m"
